name: melb_foot_traffic
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pandas
  - numpy
  - jupyter
  - geopandas
  - shapely
  - pyproj
  - rtree
  - fiona
  - gdal
  - matplotlib
  - requests
  - scikit-learn
  - pip:
      - nbformat
      - pytest
